name: CI-CD

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Running unit tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 16.20.2
        uses: actions/setup-node@v4
        with:
          node-version: "16.20.2"

      - name: Install dependencies
        working-directory: backend
        run: npm i

      - name: Set up .env file
        working-directory: backend
        run: echo "My variable is ${{ vars.NODE_ENV_MONGODB_URI_CONNECTION }}"

      - name: Run unit tests
        working-directory: backend
        run: npm run test
