name: CI-CD

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Running unit tests
    runs-on: ubuntu-latest
    env:
      DB_CONNECTION_STRING: ${{ secrets.NODE_ENV_MONGODB_URI_CONNECTION }} # Referência à variável de ambiente do GitHub

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 16.20.2
        uses: actions/setup-node@v4
        with:
          node-version: "16.20.2"

      - name: Install dependencies
        working-directory: backend
        run: npm i

      - name: Set up .env file
        working-directory: backend
        run: echo "DB_CONNECTION_STRING=${DB_CONNECTION_STRING}" >> .env

      - name: Run unit tests
        working-directory: backend
        run: npm run test
